### ISSUE TITLE
 Failed to install insomnia-plugin-terminal-command

### ISSUE THREAD

**Issue by vKolerts** [vimekk/insomnia-plugin-terminal-command#1]
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}

    at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)
    at async onSubmit (file:///opt/Insomnia/resources/app.asar/mainWindow-CnaQkWW6.js:1444:66352)

**Comment by vimekk** [comment]
Hi, 

Could you provide more details? 
Like the insomnia version or operating system you try to install the plugin.

**Comment by vKolerts** [comment]
Version: Insomnia 10.1.1
Build date: 24.10.2024
OS: Linux x64 6.6.54-2-MANJARO
Electron: 31.4.0
Node: 20.16.0
Node ABI: 125
V8: 12.6.228.30-electron.0
Architecture: x64

**Comment by vimekk** [comment]
I am able to reproduce the issue. 
I've updated the package. Could you try with a new version of package?

**Comment by vKolerts** [comment]
Please add to package.json
```
"dependencies": {
    "jsonpath": "^1.1.1"
  },```

**Comment by vimekk** [comment]
It's already [there](https://github.com/vimekk/insomnia-plugin-terminal-command/blob/17912a1fdb43a713e2598a37df7973e482888dfd/package.json#L20-L22)
